@echo off
if "%1"=="\" cd \
if "%1"=="/" cd "%SCRIPTS%"
if "%1"=="b" cd "%SCRIPTS%"
if "%1"=="d" cd "%SCRIPTS%\dev"
if "%1"=="dev" cd "%SCRIPTS%\dev"
if "%1"=="l" cd "%SCRIPTS%\lib"
if "%1"=="lib" cd "%SCRIPTS%\lib"
if "%1"=="test" cd "%SCRIPTS%\test\unit"
if "%1"=="netsh" cd "%SCRIPTS%\dev\netsh"
if "%1"=="t" cd "\tmp"
if "%1"=="tmp" cd "%TMP%"
if "%1"=="app" cd "%APPDATA%"
if "%1"=="all" cd "%ALLUSERSPROFILE%"
if "%1"=="home" cd "%USERPROFILE%"
if "%1"=="mydoc" cd "%USERPROFILE%\My Documents"
if "%1"=="mypic" cd "%USERPROFILE%\My Documents\My Pictures"
if "%1"=="mymusic" cd "%USERPROFILE%\My Documents\My Music"
if "%1"=="win" cd "%systemroot%"
if "%1"=="sys" cd "%systemroot%\system32"
if "%1"=="hosts" cd "%systemroot%\system32\drivers\etc"
if "%1"=="cron" cd "%systemroot%\cronNT"
if "%1"=="pro" cd "%ProgramFiles%"
if "%1"=="wintool" cd "%ProgramFiles%\WINTOOLS"
if "%1"=="openssh" cd "%ProgramFiles%\OpenSSH\etc"
if "%1"=="cron" cd "\cron"
if "%1"=="ftp" cd "\ftp"
if "%1"=="putin" cd "\ftp\putin"
if "%1"=="down" cd "\ftp\download"
if "%1"=="mysql" cd "\mysql\bin"
if "%1"=="postgres" cd "\PostgreSQL\bin"
if "%1"=="http" cd "\http"
if "%1"=="www" cd "\www"
if "%1"=="cgi" cd "\cgi-bin"
if "%1"=="img" cd "\img"
if "%1"=="apache" cd "\Apache2\conf"
if "%1"=="perl" cd "\Perl\bin"
if "%1"=="php" cd "\php"
if "%1"=="python" cd "\Python24\Scripts"
if "%1"=="ruby" cd "\ruby\bin"
if "%1"=="vim" cd "\vim"
if "%1"=="svn" cd "\svnwork"
if "%1"=="svnwork" cd "\svnwork"
if "%1"=="ssh" cd "%USERPROFILE%\.ssh"
if "%1"=="svk" cd "%USERPROFILE%\.svk"
if "%1"=="java" cd "%JAVA_HOME%"
if "%1"=="eclipse" cd "%ECLIPSE_HOME%"
if "%1"=="tomcat" cd "%CATALINA_HOME%"
if "%1"=="var" cd "\var"
if "%1"=="log" cd "\var\log"
if "%1"=="shared" cd "\shared"
if "%1"=="music" cd "\largefiles\musicfiles"
if "%1"=="sns" cd "\sns"
if "%1"=="mixi" cd "\sns\mixi"
if not "%1"=="" dir /od %2 %3 %4 %5 %6 %7 %8 %9
if "%1"=="" cls
cd
