@echo off
echo [SystemDrive] %SystemDrive%
echo [SystemRoot] %SystemRoot%
echo [COMPUTERNAME] %COMPUTERNAME%
echo [OS] %OS%
echo [PROMPT] %PROMPT%
echo [TMP] %TMP%
echo [TEMP] %TEMP%
echo [USERPROFILE] %USERPROFILE%
echo [USERNAME] %USERNAME%
echo [USERDOMAIN] %USERDOMAIN%
echo [HTTP_PROXY] %HTTP_PROXY%
echo [FTP_PROXY] %FTP_PROXY%
echo [RUBY] %RUBY%
echo [RUBYOPT] %RUBYOPT%
echo [SCRIPTS] %SCRIPTS%
echo [CLASSPATH] %CLASSPATH%
echo [PATH] %PATH%
echo [PATHEXT] %PATHEXT%
