name: Run Python and Ruby Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.11]
        ruby-version: ['3.1.4']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml bs4 requests Pillow

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Set SCRIPTS environment variable
      run: echo "SCRIPTS=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Run tests
      run: |
        chmod +x ./run_tests.sh
        ./run_tests.sh

