#!/bin/sh

sudo apt install -y amd64-microcode
sudo apt install -y firmware-amd-graphics
sudo apt install -y firmware-iwlwifi
sudo apt install -y firmware-linux
sudo apt install -y firmware-linux-nonfree
sudo apt install -y firmware-misc-nonfree
sudo apt install -y intel-microcode
sudo apt install -y libegl-nvidia0
sudo apt install -y libgl1-nvidia-glvnd-glx
sudo apt install -y libgles-nvidia1
sudo apt install -y libgles-nvidia2
sudo apt install -y libglx-nvidia0
sudo apt install -y libnvidia-cbl
sudo apt install -y libnvidia-cfg1
sudo apt install -y libnvidia-eglcore
sudo apt install -y libnvidia-fatbinaryloader
sudo apt install -y libnvidia-glcore
sudo apt install -y libnvidia-glvkspirv
sudo apt install -y libnvidia-ml1
sudo apt install -y libnvidia-ptxjitcompiler1
sudo apt install -y libnvidia-rtcore
sudo apt install -y nvidia-alternative
sudo apt install -y nvidia-detect
sudo apt install -y nvidia-driver
sudo apt install -y nvidia-driver-bin
sudo apt install -y nvidia-driver-libs
sudo apt install -y nvidia-egl-common
sudo apt install -y nvidia-egl-icd
sudo apt install -y nvidia-kernel-dkms
sudo apt install -y nvidia-kernel-support
sudo apt install -y nvidia-legacy-check
sudo apt install -y nvidia-smi
sudo apt install -y nvidia-vdpau-driver
sudo apt install -y nvidia-vulkan-common
sudo apt install -y nvidia-vulkan-icd
sudo apt install -y xserver-xorg-video-nvidia
sudo apt install -y glx-alternative-mesa
sudo apt install -y glx-alternative-nvidia
sudo apt install -y glx-diversions
sudo apt install -y iucode-tool
sudo apt install -y nvidia-installer-cleanup
sudo apt install -y nvidia-kernel-common
sudo apt install -y nvidia-modprobe
sudo apt install -y nvidia-persistenced
sudo apt install -y nvidia-settings
sudo apt install -y nvidia-support
sudo apt install -y update-glx

