
# sudo R --no-save --no-restore < ~/scripts/installer/install_R-libs.R

options(repos="http://cran.ism.ac.jp")

install.packages('randomForest')
install.packages('plyr')
install.packages('reshape2')
install.packages('forecast')
install.packages('stringr')
install.packages('lubridate')
install.packages('sqldf')
install.packages('ggplot2')
install.packages('qcc')
install.packages('party')
install.packages('gbm')
install.packages('survival')
install.packages('caTools')
install.packages('Epi')
install.packages('XLConnect')
install.packages('DMwR')

install.packages('aod')
install.packages('car')
install.packages('coda')
install.packages('date')
install.packages('e1071')
install.packages('faraway')
install.packages('geoRglm')
install.packages('glmmML')
install.packages('gplots')
install.packages('Hmisc')
install.packages('labdsv')
install.packages('lme4')
install.packages('R2WINBUGS')
install.packages('scatterplot3d')
install.packages('lme4')
install.packages('smatr')
install.packages('vegan')
install.packages('xtable')

install.packages('sem')
install.packages('TTR')
install.packages('biOps')
install.packages('igraph')
install.packages('kernlab')
install.packages('lattice')
install.packages('mvtnorm')
install.packages('plotrix')
install.packages('pracma')
install.packages('quadprog')
install.packages('tseries')
install.packages('xts')
install.packages('zoo')

install.packages('classInt')
install.packages('gpclib')
install.packages('maptools')
install.packages('mapproj')
install.packages('maps')

library()

